version: 0.2
run-as: root


phases: 
    pre_build: 
      commands: 
        - "echo Logging in to Docker Hub..."
        - "aws --version"
        - "echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin"
    build: 
      commands: 
        - "echo Build started on `date`"
        - "echo Building the Docker image..."
        - "docker build -t johna1/test ."
    post_build: 
      commands: 
        - "echo Build completed on `date`"
        - "echo Pushing the Docker image..."
        - "docker push johna1/test"
        - "echo Writing image definitions file..."
        - "printf '[{\"name\":\"%s\",\"imageUri\":\"%s\"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json"
artifacts: 
  files: imagedefinitions.json
